[package]
name = "rust"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/AsahiLinux/m1n1"
license = "MIT"
publish = false

[lib]
crate-type = [ "staticlib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
fatfs = { git = "https://github.com/aurora-silicon/fatfs", rev = "7d505fbfa37a945af5549517f47c1d2e87a8333e", default-features = false, features = ["lfn", "alloc", "explicit-fat32"], optional = true }
sha1_smol = { version = "1.0.1" }
uuid = {  version = "1.23", default-features = false, optional = true }
versions = { path = "./versions" }

[features]
chainload = ["dep:fatfs", "dep:uuid"]
